//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto1Segunda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sinopse { get; set; }
        public bool Ativo { get; set; }
        public int GeneroId { get; set; }
    
        public virtual Genero Genero { get; set; }
    }
}
